#pragma once

//TODO: rename later

#define SERVICE_CONTROL_USER 128

#define OSR_COMM_DATA_TYPE 45935
#define OSR_COMM_CONTROL_TYPE 45936

#define OSR_COMM_CONTROL_GET_REQUEST CTL_CODE(OSR_COMM_CONTROL_TYPE, 3192, METHOD_BUFFERED, FILE_READ_ACCESS)
#define OSR_COMM_CONTROL_SEND_RESPONSE CTL_CODE(OSR_COMM_CONTROL_TYPE, 3193, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define OSR_COMM_CONTROL_GET_AND_SEND CTL_CODE(OSR_COMM_CONTROL_TYPE, 3194, METHOD_BUFFERED, FILE_READ_ACCESS|FILE_WRITE_ACCESS)